/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lights_off_alexandre;

import java.util.Random;

/**
 *
 * @author jason
 */
public class fenetredejeu extends javax.swing.JFrame {
    Grille GrilleJeu=new Grille() ;
    /**permet de placer les 25 bouttons
     * Creates new form fenetredejeu
     */
    public fenetredejeu() {
        initComponents();
        for (int i=4;i>=0;i--){
            for (int j=0;j<5;j++){
                Cellulegraph cellgraph =new Cellulegraph(GrilleJeu.cellules[i][j]);
                Panelgrille.add(cellgraph);
            } 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panelgrille = new javax.swing.JPanel();
        Panelinfojeu = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panelgrille.setBackground(new java.awt.Color(51, 51, 51));
        Panelgrille.setLayout(new java.awt.GridLayout(5, 5));
        getContentPane().add(Panelgrille, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 480, 480));

        Panelinfojeu.setBackground(new java.awt.Color(204, 204, 204));
        Panelinfojeu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Lancer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Panelinfojeu.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        getContentPane().add(Panelinfojeu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 360, 60));

        setBounds(0, 0, 714, 607);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        initialiserpartie();
        Panelgrille.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fenetredejeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fenetredejeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fenetredejeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fenetredejeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fenetredejeu().setVisible(true);
            }
        });
    }

    /**
     *initialise la partie en generant aleatoirement des cases allumees
     * @param cellules
     */
    public void initialiserpartie(){
        GrilleJeu.random();
        
      
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panelgrille;
    private javax.swing.JPanel Panelinfojeu;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
